# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: zip -r testVeracode.zip . -x ./node_modules/\*
  displayName: 'Zip application to scan'

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'odp-cds-veracode-analysis'
    veracodeAppProfile: 'ODP - Microservices'
    version: '$(build.buildNumber)'
    filepath: '$(System.DefaultWorkingDirectory)/testVeracode.zip'
    optargs: '-fail_on_severity="Very High, High, Medium"'
    failTheBuildIfVeracodeScanDidNotInitiate: true
    maximumWaitTime: '360'
    importResults: true
    failBuildOnPolicyFail: true

    
