# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: Veracode account credentials

steps:
- powershell: |
    $repositoryName = "$(Build.Repository.Name)" -replace "/", "_"  
    echo "##vso[task.setvariable variable=repositoryName;isOutput=true]$repositoryName"
  name: slashReplacer

- bash: zip -r $(slashReplacer.repositoryName).zip . -x ./node_modules/\*
  displayName: 'Zip application to scan'

- bash: curl -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
  displayName: Download the Pipeline Scanner

- bash: unzip pipeline-scan-LATEST.zip -d $(System.DefaultWorkingDirectory)/veracode
  displayName: Unzip the Pipeline Scanner

- bash: java -jar $(System.DefaultWorkingDirectory)/veracode/pipeline-scan.jar
        --file $(System.DefaultWorkingDirectory)/$(slashReplacer.repositoryName).zip
        --project_name "$(slashReplacer.repositoryName)"
        --veracode_api_id "$(api_id)"
        --veracode_api_key "$(api_key)"
        --fail_on_severity="Very High, High, Medium"
  displayName: Run Pipeline Scanner