# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

- script: zip -r $(system.teamProject).zip $(pipeline.workspace) -x ./node_modules/\*
  displayName: 'Zip application to scan'

- task: Veracode@3
  inputs:
    ConnectionDetailsSelection: 'Endpoint'
    AnalysisService: 'odp-cds-veracode-analysis'
    veracodeAppProfile: '$(system.teamProject)'
    version: '$(build.buildNumber)'
    filepath: '$(pipeline.workspace)'
    failTheBuildIfVeracodeScanDidNotInitiate: true
    failBuildOnPolicyFail: true
    maximumWaitTime: '360'
    
